import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { BsGrid3X3GapFill } from 'react-icons/bs'
import axios from 'axios'
import {useState} from 'react'
import {BsSearch} from 'react-icons/bs'


export default function Home() {

  const[location, setLocation] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)

  const url = `https://api.weather.gov/points/${location}`

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })

    setLocation('')
    setLoading(false)
  }

  return (
    <div>
      <Head>
        <title>Dustin Long Weather App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href='/favicon.ico'/>
      </Head>

{/* Overlay */}

<div className='absolute top-0 left-0 right-0 bottom-0 bg-black/30 z-[1]'/>

{/* Background Image */}

      <Image className='object-cover' src='https://images.unsplash.com/photo-1496450681664-3df85efbd29f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80' fill/>

      <button onClick={fetchWeather}>Fetch data</button>

      {/* Search */}

      <div className='relative flex justify-between items-center max-w-[400px] w-full m-auto pt-4 text-white z-10'>
        <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-slate-400 rounded-xl'>
          <div>
            <input 
            onChange={(e)=> setLocation(e.target.value)}
            className='bg-transparent border-none text-white focus:outline-none text-xl placeholder:text-gray-400' 
            type="text" 
            placeholder='Search location'/>
          </div>
          <button onClick={fetchWeather}>
            <BsSearch size={20}/>
            </button>
        </form>
      </div>

    </div>
  )
}